server:
  port: 8092
  application:
    name: test-app
swagger:
  title: Best Deal Bank
  description: Endpoints available for Best Deal Bank
  path: /api/.*
  
logging:
  file: ../logs/$(spring.application.name}.log
---
spring:
  profiles: dev
  
logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE